[global]
    server string = samba
    idmap config * : range = 3000-7999
    security = user
    server min protocol = SMB2
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

[homes]
    comment = Home Directories
    browseable = no
    read only = no
    create mask = 0700
    directory mask = 0700
    valid users = %S

[test_share]
    path = /storage
    comment = Shared
    valid users = testuser
    browseable = yes
    writable = yes
    read only = no
    force user = root
    force group = root
